### ISSUE TITLE
Create config folder

### ISSUE THREAD

**Issue by arsavinel** [arshwell/monolith#1]
An idea would be putting env and forks in the same subfolder. It would be a better file structure.

I have noticed Symfony framework does that. Because, as far as I understand, these configs could use Environment Variables, and, for that, an .env file is used, in root of the project. So we should move the env.json content inside a config subfolder.

___

Config structure suggestion:

| config/
| --- | forks/
| --- | --- | 1.site.json
| --- | --- | 2.cms.json
| --- | --- | 3.404.json
| --- | databases.json *(connections, backups)*
| --- | development.json *(debug, credits, ips)*
| --- | services.json *(translation, migration, maintenance, ...)*
| --- | locations.json *(paths)*
| --- | web.json *(URL, SSL)*

___

One class, named `Arshwell\Monolith\Env\EnvConfig`, will store the configs.

A static handler, `Arshwell\Monolith\StaticHandler`, will store the EnvConfig object.

There will be no .env params for the moment. There is another issue, #2, for that.

Other scalable config logic should be made after this implementation, using another issue.

___

**Note:** Don't change routes logic at all. Not even the folder name.
*It should be implemented using another issue.*

**Note:** `env.json => "mail"` keyword will be deleted. It should be created an abstract Mail class for that.
*It should be implemented using another issue.*

**Note:** `config/web.json => "SSL"` could have these values: "yes", "no", "auto".
*It should be implemented using another issue.*

**Note:** order of parsing routes files must be specified using a service.
*It should be implemented using another issue.*

**Note:** order of recompiling routes css/js files must be specified using a service. Because user-side routes should have priority.
*It should be implemented using another issue.*

___

_Note: this task is part of the milestone named [Scalable environment configs](https://github.com/arshwell/monolith/milestone/1)._

**Comment by arshavinel** [comment]
I've started refactoring the `Mail::class`.

I am just replacing the `env.json => "mail"` usage with abstract methods.

The rest of implementation will be made in another issue.
