### ISSUE TITLE
Make environments configurable

### ISSUE THREAD

**Issue by arsavinel** [arshwell/monolith#2]
**Note:** this task requires task #1 to be done.

___

As far as I read, Symfony framework uses .env (and .env.local) as storage of Environment Variables. These are probably used in config/ files. I need to research more on that.

First file (.env) has general variables used by all environments (local, stage, prod).

Second file (.env.local) has only those for your environment (machine), like your local DB credentials. This is ignored by git and created by developer locally.

___

Also, I have noticed that GitHub Actions can use Environment Variables you define. And they can be grouped by environments (ex: local, stage, prod).

I guess these ones overwrite those from .env.

___

**Task:** I must read more on:

- how this .env file is used;
- these variables can interact only with .yaml files?
- how are actually GitHub Environment Variables used in GitHub Actions.

___

One class, named `ArshWell\Monolith\Env\EnvConfig`, comes from #1 issue.

The object will replace the env params using `ArshWell\Monolith\Env\EnvParams` object. Which will look for them into `.env` and `.env.local` files.

___

_Note: this task is part of the milestone named [Scalable environment configs](https://github.com/arshwell/monolith/milestone/1)._

**Comment by arshavinel** [comment]
Answers for myself:

1. I have searched more about the .env file. It stores variables which are used by config files.

2. The placeholders logic, in config files, I can choose myself. And also the .env parsing logic.
    - i want them custom for now so I can understand better how they works.
    - _sometime in the future and I can use composer packages just for that (if I want to)._

3. I can use a GitHub action to copy GitHub Environment Variables in .env.local file.
    - this file overwrites .env file, having data related to the environment (ex: dev, staging, production).

___

GitHub Actions: Approvals, Environments and Visualization
https://www.youtube.com/watch?v=w_37LDOy4sI

**Comment by arshavinel** [comment]
I will use `symfony/dotenv` package to parse the .env and .env.local files. This package stores the variables in the $_ENV global variable.
